#!/bin/bash

# omarchy:summary=Launch a URL as a web app in the default supported browser
# omarchy:args=<url>

browser=$(xdg-settings get default-web-browser)
browser_exec=$(sed -n 's/^Exec=\([^ ]*\).*/\1/p' {~/.local,~/.nix-profile,/usr}/share/applications/$browser 2>/dev/null | head -1)

case $browser in
google-chrome* | brave* | microsoft-edge* | opera* | vivaldi* | chromium* | helium*)
  exec setsid uwsm-app -- "$browser_exec" --app="$1" "${@:2}"
  ;;
firefox* | zen*)
  exec setsid uwsm-app -- "$browser_exec" --new-window "$1" "${@:2}"
  ;;
*)
  default_exec=$(sed -n 's/^Exec=\([^ ]*\).*/\1/p' {~/.local,~/.nix-profile,/usr}/share/applications/chromium.desktop 2>/dev/null | head -1)
  exec setsid uwsm-app -- "$default_exec" --app="$1" "${@:2}"
  ;;
esac
